language: rust
rust:
  - stable
addons:
  apt:
    packages:
    - openvpn

before_install:
  - sudo openvpn path/to/conf.ovpn &>>openvpn-client.log &

before_script:
  # the script below adds an environment variable to the shell
  # it's important to "source" it (using ".") so cargo test can use the env variable
  source download_recent_itch50.sh
