on: [push, pull_request]

name: CI

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Test compiles with serde
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --features serde
